import { MigrationInterface, QueryRunner } from 'typeorm';

export class NormalizeQuestionModel231DisplayLabels1774300000000 implements MigrationInterface {
  name = 'NormalizeQuestionModel231DisplayLabels1774300000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      UPDATE checkup_question_macro_areas macro
      JOIN checkup_question_models model ON model.id = macro.modelId
      SET macro.label = TRIM(REGEXP_REPLACE(macro.label, '^[A-Z][[:space:]]*[-–—:.][[:space:]]*', ''))
      WHERE model.code = '231'
    `);

    await queryRunner.query(`
      UPDATE checkup_question_sections section
      JOIN checkup_question_macro_areas macro ON macro.id = section.macroAreaId
      JOIN checkup_question_models model ON model.id = macro.modelId
      SET section.title = TRIM(
        REGEXP_REPLACE(
          REGEXP_REPLACE(section.title, '^M[.]231[[:space:]]*[-–—:][[:space:]]*', ''),
          '^[A-Z][.]([0-9]+)([.][0-9]+)?[[:space:]]*[-–—:]?[[:space:]]*',
          ''
        )
      )
      WHERE model.code = '231'
    `);
  }

  public async down(): Promise<void> {
    // Irreversible normalization: prefixes are now generated by display order.
  }
}
